remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
# title: "Alexander Jahn"
title_separator: "-"
# subtitle: "Software Dev"
name: &name "Alexander Jahn" # &name is a YAML anchor which can be *referenced later
description: &description "A flexible Jekyll theme for your blog or site with a minimalist aesthetic."
url: https://alxndrjhn.github.io/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/"
repository: "AlxndrJhn/AlxndrJhn.github.io"
teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo: "/assets/logo.svg" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title: # overrides the website title displayed in the masthead, use " " for no title

# SEO Related
google_site_verification: "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y" # Replace this with your ID, or delete

# Social Sharing
twitter:
  username: &twitter "alxndr__jhn"

og_image: "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/alxndr__jhn"

# Analytics
analytics:
  provider: "google-universal" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "UA-2011187-3" # Replace this with your ID, or delete
    anonymize_ip: true

# Site Author
author:
  name: *name # *name is a YAML reference pointing to the &anchor earlier
  avatar: "/assets/landing/Alexander_Jahn.jpg"
  bio: "Software Dev with background in robotics"
  location: "Cologne, Germany"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/alexander-jahn-7849b7a8/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/alxndr__jhn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AlxndrJhn"

# Site Footer
footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/alexander-jahn-7849b7a8/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/alxndr__jhn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AlxndrJhn"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  recipes:
    output: true
    permalink: /:collection/:path/
  pets:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
