# Site settings
title: Alexander Jahn
email: aj@alexander-jahn.org
description: > # this means to ignore newlines until "baseurl:"
  This is my public CV, portfolio and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alxndrjhn.github.io/" # the base hostname & protocol for your site
twitter_username: alxndr__jhn
github_username:  AlxndrJhn

plugins:
  - jekyll-include-cache

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
markdown: kramdown
