source "https://rubygems.org"
gem "minimal-mistakes-jekyll"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages"

gem 'bootstrap-sass'
gem 'jekyll-bootstrap-sass'

gem "kramdown-parser-gfm"
